nearai agent dev command starts local UI
nearai/nearai pull request #634
Opened 2024-12-10 01:50 UTC by gabehamilton

2024-12-10 13:39 UTC, zavodil commented
I like this idea!

Shall we try to open http://localhost:3000 automatically?

And the choice of name for this command is not entirely clear. Previously, for `nearai agent`, we specified the agent's name (or path), but here we don't do that. Additionally, the command `dev` doesn't seem to associate with launching any kind of UI for me. Perhaps something like `nearai hub` or `nearai ui` would be more intuitive to me.

2024-12-10 15:53 UTC, calebjacob requested changes
Nice work! Left one comment to work through.

2024-12-10 15:53 UTC, calebjacob commented on nearai/cli.py
> +        ret_val = os.system("npm run dev --prefix hub/demo")
Can this simply be `npm run dev`? I'm not sure what `--prefix hub/demo` is adding here unless I'm totally missing something.

We also need to run `npm i` to install dependencies. Maybe we change to `ret_val = os.system("npm i && npm run dev")`.

Also, the UI requires a minimum of Node 18 - might be worth mentioning somewhere.

I'm not sure how the Python registry works for `pip install nearai`. We'll want to make sure all of `hub/demo`'s source code is published and `nearai dev` works as expected when installed that way.

2024-12-12 19:57 UTC, calebjacob approved these changes
Looks good to start with! We can keep making this more robust with future PRs.

2024-12-12 19:58 UTC, merged